version: "1.1"
services:
  php:
    build:
      dockerfile: PHP.Dockerfile
      context: .
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysqldata:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
volumes:
  mysqldata:
